name: Bug Report
description: Report something that isn't working correctly
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report this.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      placeholder: |
        1. Create a store with ...
        2. Insert a document ...
        3. Query with ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`
      placeholder: go1.23.0 linux/amd64
    validations:
      required: true

  - type: input
    id: whisker-version
    attributes:
      label: Whisker version
      description: The version or commit hash you're using.
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: pg-version
    attributes:
      label: PostgreSQL version
      description: Output of `SELECT version();`
      placeholder: PostgreSQL 16.2
    validations:
      required: false
